In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 과거의 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

In [3]:
# 독립변수, 종속변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [5]:
# 모델의 구조 만들기
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [9]:
# 모델 구조 확인
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [8]:
# 데이터로 모델 학습(FIT)
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 13.5280
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 13.0112
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 12.5774
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 13.3161
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 13.4013
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 12.1024
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 13.3772
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 14.0169
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 12.8088
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 12.7631


In [10]:
# 모델 이용
print(model.predict(독립[:5]))
print(종속[:5])

[[32.735447]
 [23.87138 ]
 [32.764244]
 [34.45093 ]
 [31.901506]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [ ]:
################################################################################

In [11]:
# 과거의 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

In [12]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

In [13]:
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [14]:
# 모델 구조 만들기
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [15]:
# 모델 구조 확인
model.summary()

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [16]:
# 데이터로 모델 학습(FIT)
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 1.5057 - accuracy: 0.3333
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 1.2271 - accuracy: 0.3333
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0815 - accuracy: 0.3333
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9855 - accuracy: 0.3533
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9214 - accuracy: 0.4733
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8729 - accuracy: 0.6333
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8332 - accuracy: 0.6667
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.7999 - accuracy: 0.6667
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.7662 - accuracy: 0.6667
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.7347 - accuracy: 0.6667
Epoch 11/100
5/5 [===========

In [17]:
# 모델 이용
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9617779e-01 3.8220405e-03 1.0452708e-07]
 [9.9322432e-01 6.7753037e-03 3.7442248e-07]
 [9.9501991e-01 4.9798177e-03 2.9348729e-07]
 [9.9323153e-01 6.7679714e-03 4.6655504e-07]
 [9.9643034e-01 3.5695147e-03 1.0131206e-07]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
